name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore ./MySolution.sln
    - name: Build
      run: dotnet build ./MySolution.sln --no-restore
    - name: Test
      run: dotnet test ./MySolution.sln --no-build --verbosity normal
